# Generated by Django 5.2.4 on 2025-12-03 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(default='dummy', help_text='Nombre del proveedor biométrico (dummy, facephi, etc.)', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('exitosa', 'Exitosa'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('score', models.FloatField(blank=True, help_text='Confianza reportada por el proveedor (0–1, 0–100, etc.)', null=True)),
                ('razon', models.CharField(blank=True, help_text='Mensaje explicando por qué falló o cualquier info del proveedor.', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('verificado_en', models.DateTimeField(blank=True, null=True)),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones_biometricas', to='wallet.sesion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones_biometricas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_frente', models.ImageField(blank=True, null=True, upload_to='kyc/dni_frente/')),
                ('dni_dorso', models.ImageField(blank=True, null=True, upload_to='kyc/dni_dorso/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QRPaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moneda', models.CharField(default='ARS', max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('referencia_externa', models.CharField(blank=True, help_text='Para mapear a IDs de Transferencias 3.0 / PSP en el futuro.', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_cobro_qr', to='wallet.cuenta')),
            ],
        ),
    ]
