# Generated by Django 5.2.4 on 2025-12-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_biometricverification_kycverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='referencia',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
