# Generated by Django 5.2.4 on 2025-12-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_cuenta_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
